-- 1. Tabel user_sessions (Untuk simpan Device ID & Token)
create table if not exists user_sessions (
  id bigint generated by default as identity primary key,
  nip text unique not null,
  device_id text,
  token text,
  full_name text,
  updated_at timestamp with time zone default now()
);
alter table user_sessions enable row level security;
drop policy if exists "Enable all for user_sessions" on user_sessions;
create policy "Enable all for user_sessions" on user_sessions for all using (true) with check (true);

-- 2. Tabel allowed_nips (Whitelist Login Pegawai)
create table if not exists allowed_nips (
  id bigint generated by default as identity primary key,
  nip text unique not null,
  created_at timestamp with time zone default now()
);
alter table allowed_nips enable row level security;
drop policy if exists "Enable all for allowed_nips" on allowed_nips;
create policy "Enable all for allowed_nips" on allowed_nips for all using (true) with check (true);

-- 3. Tabel office_admins (Daftar Admin Kantor)
create table if not exists office_admins (
  id bigint generated by default as identity primary key,
  nip text unique not null,
  created_at timestamp with time zone default now()
);
alter table office_admins enable row level security;
drop policy if exists "Enable all for office_admins" on office_admins;
create policy "Enable all for office_admins" on office_admins for all using (true) with check (true);

-- 4. Contoh Insert NIP (Opsional)
-- insert into allowed_nips (nip) values ('199001012015011001') on conflict (nip) do nothing;